# Grafana datasource configuration for Prometheus
# Automatic provisioning of Prometheus data source

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
    editable: true
    
  - name: Prometheus-Local
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: false
    jsonData:
      httpMethod: GET
      queryTimeout: 30s
      timeInterval: 5s
    editable: true